#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.fresh/build/shell.sh
alias nonprod="aws --profile nonprod ec2 describe-instances | jq '.Reservations[].Instances[] | { id: .InstanceId, private_ip: .PrivateIpAddress, tags: .Tags }' | less"
alias prod="aws --profile production ec2 describe-instances | jq '.Reservations[].Instances[] | { id: .InstanceId, private_ip: .PrivateIpAddress, tags: .Tags }' | less"
alias services="aws --profile services ec2 describe-instances | jq '.Reservations[].Instances[] | { id: .InstanceId, private_ip: .PrivateIpAddress, tags: .Tags }' | less"

# Docker
#eval "$(docker-machine env dinghy)"

pad() { sed 's/^/  /'; }
#alias ls="CLICOLOR_FORCE=1 ls -G | pad"
